sudo: false
language: node_js
cache:
  directories:
    - node_moudules
node_js: 6
branches:
  only:
    - master
notifications:
  email: false
script:
  npm run validate
after_succss:
  - npm run report-coverage
